ACCESS_KEY_ID = "x"
SECRET_ACCESS_KEY = "x"
INPUT_BUCKET = "imageinputbucket"
OUTPUT_BUCKET = "imageoutputbucket"
INPUT_QUEUE = "https://sqs.us-east-1.amazonaws.com/051675418934/Input-Image-Queue.fifo"